CREATE TABLE IF NOT EXISTS flight_source_inbox (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    provider VARCHAR(64) NOT NULL,
    record_type VARCHAR(16) NOT NULL,
    external_record_id VARCHAR(128) NOT NULL,
    external_flight_id VARCHAR(128) NOT NULL,
    flight_display_no VARCHAR(64) NULL,
    operating_date DATE NULL,
    scheduled_at DATETIME(6) NULL,
    event_status VARCHAR(32) NULL,
    occurred_at DATETIME(6) NULL,
    actual_arrival_at DATETIME(6) NULL,
    actual_departure_at DATETIME(6) NULL,
    reason VARCHAR(255) NULL,
    payload JSON NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    attempts INT UNSIGNED NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    lease_owner VARCHAR(128) NULL,
    lease_expires_at DATETIME(6) NULL,
    applied_at DATETIME(6) NULL,
    last_error VARCHAR(1024) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_flight_source_inbox_public_id (public_id),
    UNIQUE KEY uk_flight_source_inbox_external (provider, record_type, external_record_id),
    KEY idx_flight_source_inbox_status_next (status, next_attempt_at, id),
    KEY idx_flight_source_inbox_flight (provider, external_flight_id, record_type),
    CONSTRAINT chk_flight_source_inbox_type CHECK (record_type IN ('schedule', 'event')),
    CONSTRAINT chk_flight_source_inbox_status CHECK (status IN ('pending', 'processing', 'retry', 'applied', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
