CREATE TABLE IF NOT EXISTS task_exception (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    assignment_id BIGINT UNSIGNED NOT NULL,
    personnel_id BIGINT UNSIGNED NOT NULL,
    category VARCHAR(64) NOT NULL,
    severity VARCHAR(16) NOT NULL,
    description VARCHAR(1024) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'open',
    reported_by_public_id CHAR(36) NOT NULL,
    reported_at DATETIME(6) NOT NULL,
    resolved_by_public_id CHAR(36) NULL,
    resolved_at DATETIME(6) NULL,
    resolution_note VARCHAR(1024) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_exception_public_id (public_id),
    KEY idx_task_exception_task (task_id, reported_at),
    KEY idx_task_exception_assignment (assignment_id, reported_at),
    KEY idx_task_exception_status (status, severity, reported_at),
    CONSTRAINT fk_task_exception_task FOREIGN KEY (task_id) REFERENCES task_instance (id),
    CONSTRAINT fk_task_exception_assignment FOREIGN KEY (assignment_id) REFERENCES task_assignment (id),
    CONSTRAINT fk_task_exception_personnel FOREIGN KEY (personnel_id) REFERENCES personnel (id),
    CONSTRAINT chk_task_exception_severity CHECK (severity IN ('low', 'medium', 'high', 'critical')),
    CONSTRAINT chk_task_exception_status CHECK (status IN ('open', 'acknowledged', 'resolved', 'rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
