CREATE TABLE IF NOT EXISTS operation_area (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_operation_area_public_id (public_id),
    UNIQUE KEY uk_operation_area_code (code),
    CONSTRAINT chk_operation_area_enabled CHECK (enabled IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS team (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    area_id BIGINT UNSIGNED NOT NULL,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_team_public_id (public_id),
    UNIQUE KEY uk_team_area_code (area_id, code),
    KEY idx_team_area_enabled (area_id, enabled),
    CONSTRAINT fk_team_area FOREIGN KEY (area_id) REFERENCES operation_area (id),
    CONSTRAINT chk_team_enabled CHECK (enabled IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS personnel (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    user_public_id CHAR(36) NOT NULL,
    employee_no VARCHAR(64) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    position_code VARCHAR(64) NOT NULL,
    capabilities JSON NOT NULL,
    work_state VARCHAR(32) NOT NULL DEFAULT 'idle',
    status_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_state_changed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    unavailable_reason VARCHAR(255) NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_personnel_public_id (public_id),
    UNIQUE KEY uk_personnel_user_public_id (user_public_id),
    UNIQUE KEY uk_personnel_employee_no (employee_no),
    KEY idx_personnel_team_state (team_id, work_state, enabled),
    KEY idx_personnel_state_changed (work_state, last_state_changed_at),
    CONSTRAINT fk_personnel_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT chk_personnel_work_state CHECK (work_state IN ('idle', 'reserved', 'busy', 'unavailable')),
    CONSTRAINT chk_personnel_enabled CHECK (enabled IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS team_member (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    personnel_id BIGINT UNSIGNED NOT NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 1,
    joined_at DATETIME(6) NOT NULL,
    left_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_team_member_public_id (public_id),
    UNIQUE KEY uk_team_member_period (team_id, personnel_id, joined_at),
    KEY idx_team_member_personnel (personnel_id, left_at),
    KEY idx_team_member_team (team_id, left_at),
    CONSTRAINT fk_team_member_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT fk_team_member_personnel FOREIGN KEY (personnel_id) REFERENCES personnel (id),
    CONSTRAINT chk_team_member_primary CHECK (is_primary IN (0, 1)),
    CONSTRAINT chk_team_member_period CHECK (left_at IS NULL OR left_at >= joined_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS flight (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    flight_display_no VARCHAR(64) NOT NULL,
    operating_date DATE NOT NULL,
    scheduled_at DATETIME(6) NOT NULL,
    actual_arrival_at DATETIME(6) NULL,
    departed_at DATETIME(6) NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'scheduled',
    status_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    last_status_changed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_flight_public_id (public_id),
    UNIQUE KEY uk_flight_operating_date_display_no (operating_date, flight_display_no),
    KEY idx_flight_status_schedule (status, scheduled_at),
    CONSTRAINT chk_flight_status CHECK (status IN ('scheduled', 'arrived', 'departed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS flight_status_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    flight_id BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NOT NULL,
    transition_type VARCHAR(64) NOT NULL,
    source_event_id VARCHAR(128) NULL,
    actor_type VARCHAR(32) NOT NULL DEFAULT 'system',
    actor_public_id CHAR(36) NULL,
    reason VARCHAR(255) NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_flight_status_history_public_id (public_id),
    KEY idx_flight_status_history_flight (flight_id, occurred_at),
    KEY idx_flight_status_history_source (source_event_id),
    CONSTRAINT fk_flight_status_history_flight FOREIGN KEY (flight_id) REFERENCES flight (id),
    CONSTRAINT chk_flight_status_history_to CHECK (to_status IN ('scheduled', 'arrived', 'departed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_template (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    name VARCHAR(255) NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    template_version INT UNSIGNED NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    target_area_id BIGINT UNSIGNED NOT NULL,
    target_team_id BIGINT UNSIGNED NOT NULL,
    required_position_code VARCHAR(64) NOT NULL,
    required_capabilities JSON NOT NULL,
    planned_offset_seconds INT NOT NULL DEFAULT 0,
    default_message TEXT NOT NULL,
    created_by_public_id CHAR(36) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_template_public_id (public_id),
    UNIQUE KEY uk_task_template_trigger_version (trigger_type, template_version),
    KEY idx_task_template_trigger_enabled (trigger_type, enabled),
    KEY idx_task_template_team (target_team_id, enabled),
    CONSTRAINT fk_task_template_area FOREIGN KEY (target_area_id) REFERENCES operation_area (id),
    CONSTRAINT fk_task_template_team FOREIGN KEY (target_team_id) REFERENCES team (id),
    CONSTRAINT chk_task_template_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT chk_task_template_offset CHECK (planned_offset_seconds >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_instance (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    flight_id BIGINT UNSIGNED NOT NULL,
    template_id BIGINT UNSIGNED NOT NULL,
    area_id BIGINT UNSIGNED NOT NULL,
    team_id BIGINT UNSIGNED NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    generation_key VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    source_event_id VARCHAR(128) NOT NULL,
    template_version INT UNSIGNED NOT NULL,
    task_name VARCHAR(255) NOT NULL,
    message TEXT NOT NULL,
    planned_at DATETIME(6) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'awaiting_confirmation',
    status_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    sync_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    completed_at DATETIME(6) NULL,
    cancelled_at DATETIME(6) NULL,
    cancel_reason VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_instance_public_id (public_id),
    UNIQUE KEY uk_task_instance_generation_key (generation_key),
    KEY idx_task_instance_flight (flight_id),
    KEY idx_task_instance_team_status (team_id, status, planned_at),
    KEY idx_task_instance_source_event (source_event_id),
    CONSTRAINT fk_task_instance_flight FOREIGN KEY (flight_id) REFERENCES flight (id),
    CONSTRAINT fk_task_instance_template FOREIGN KEY (template_id) REFERENCES task_template (id),
    CONSTRAINT fk_task_instance_area FOREIGN KEY (area_id) REFERENCES operation_area (id),
    CONSTRAINT fk_task_instance_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT chk_task_instance_status CHECK (status IN ('awaiting_confirmation', 'assigned', 'in_progress', 'completed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_status_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    status_version BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NOT NULL,
    reason VARCHAR(255) NULL,
    actor_type VARCHAR(32) NOT NULL DEFAULT 'system',
    actor_public_id CHAR(36) NULL,
    command_id VARCHAR(128) NULL,
    source_event_id VARCHAR(128) NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_status_history_public_id (public_id),
    UNIQUE KEY uk_task_status_history_version (task_id, status_version),
    KEY idx_task_status_history_task_time (task_id, occurred_at),
    CONSTRAINT fk_task_status_history_task FOREIGN KEY (task_id) REFERENCES task_instance (id),
    CONSTRAINT chk_task_status_history_to CHECK (to_status IN ('awaiting_confirmation', 'assigned', 'in_progress', 'completed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_candidate (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    personnel_id BIGINT UNSIGNED NOT NULL,
    candidate_rank INT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'proposed',
    matched_position_code VARCHAR(64) NOT NULL,
    matched_capabilities JSON NOT NULL,
    personnel_work_state_snapshot VARCHAR(32) NOT NULL,
    personnel_state_changed_at_snapshot DATETIME(6) NOT NULL,
    rejection_reason VARCHAR(255) NULL,
    selected_at DATETIME(6) NULL,
    invalidated_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_candidate_public_id (public_id),
    UNIQUE KEY uk_task_candidate_task_personnel (task_id, personnel_id),
    KEY idx_task_candidate_task_status_rank (task_id, status, candidate_rank),
    KEY idx_task_candidate_personnel (personnel_id),
    CONSTRAINT fk_task_candidate_task FOREIGN KEY (task_id) REFERENCES task_instance (id),
    CONSTRAINT fk_task_candidate_personnel FOREIGN KEY (personnel_id) REFERENCES personnel (id),
    CONSTRAINT chk_task_candidate_status CHECK (status IN ('proposed', 'selected', 'rejected', 'invalidated'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_assignment (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    task_id BIGINT UNSIGNED NOT NULL,
    candidate_id BIGINT UNSIGNED NOT NULL,
    personnel_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'confirmed',
    status_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    confirmation_id VARCHAR(128) NOT NULL,
    confirmed_by_public_id CHAR(36) NOT NULL,
    confirmed_at DATETIME(6) NOT NULL,
    accepted_at DATETIME(6) NULL,
    completed_at DATETIME(6) NULL,
    cancelled_at DATETIME(6) NULL,
    cancellation_id VARCHAR(128) NULL,
    cancel_reason VARCHAR(255) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_assignment_public_id (public_id),
    UNIQUE KEY uk_task_assignment_task (task_id),
    UNIQUE KEY uk_task_assignment_confirmation (confirmation_id),
    UNIQUE KEY uk_task_assignment_cancellation (cancellation_id),
    KEY idx_task_assignment_personnel_status (personnel_id, status),
    CONSTRAINT fk_task_assignment_task FOREIGN KEY (task_id) REFERENCES task_instance (id),
    CONSTRAINT fk_task_assignment_candidate FOREIGN KEY (candidate_id) REFERENCES task_candidate (id),
    CONSTRAINT fk_task_assignment_personnel FOREIGN KEY (personnel_id) REFERENCES personnel (id),
    CONSTRAINT chk_task_assignment_status CHECK (status IN ('confirmed', 'accepted', 'completed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_assignment_status_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    assignment_id BIGINT UNSIGNED NOT NULL,
    status_version BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(32) NULL,
    to_status VARCHAR(32) NOT NULL,
    reason VARCHAR(255) NULL,
    actor_type VARCHAR(32) NOT NULL DEFAULT 'system',
    actor_public_id CHAR(36) NULL,
    command_id VARCHAR(128) NULL,
    confirmation_id VARCHAR(128) NULL,
    cancellation_id VARCHAR(128) NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_assignment_history_public_id (public_id),
    UNIQUE KEY uk_task_assignment_history_version (assignment_id, status_version),
    KEY idx_task_assignment_history_assignment_time (assignment_id, occurred_at),
    CONSTRAINT fk_task_assignment_history_assignment FOREIGN KEY (assignment_id) REFERENCES task_assignment (id),
    CONSTRAINT chk_task_assignment_history_to CHECK (to_status IN ('confirmed', 'accepted', 'completed', 'cancelled'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS personnel_status_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    personnel_id BIGINT UNSIGNED NOT NULL,
    status_version BIGINT UNSIGNED NOT NULL,
    from_state VARCHAR(32) NULL,
    to_state VARCHAR(32) NOT NULL,
    reason VARCHAR(255) NULL,
    actor_type VARCHAR(32) NOT NULL DEFAULT 'system',
    actor_public_id CHAR(36) NULL,
    assignment_id BIGINT UNSIGNED NULL,
    command_id VARCHAR(128) NULL,
    occurred_at DATETIME(6) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_personnel_status_history_public_id (public_id),
    UNIQUE KEY uk_personnel_status_history_version (personnel_id, status_version),
    KEY idx_personnel_status_history_personnel_time (personnel_id, occurred_at),
    CONSTRAINT fk_personnel_status_history_personnel FOREIGN KEY (personnel_id) REFERENCES personnel (id),
    CONSTRAINT fk_personnel_status_history_assignment FOREIGN KEY (assignment_id) REFERENCES task_assignment (id),
    CONSTRAINT chk_personnel_status_history_to CHECK (to_state IN ('idle', 'reserved', 'busy', 'unavailable'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS business_idempotency_record (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    public_id CHAR(36) NOT NULL,
    operation_type VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    request_hash CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'processing',
    aggregate_type VARCHAR(64) NULL,
    aggregate_public_id CHAR(36) NULL,
    actor_type VARCHAR(32) NULL,
    actor_public_id CHAR(36) NULL,
    command_type VARCHAR(128) NULL,
    result_code VARCHAR(64) NOT NULL DEFAULT 'processing',
    result_status VARCHAR(32) NOT NULL DEFAULT 'processing',
    result_payload JSON NULL,
    error_summary VARCHAR(1024) NULL,
    request_id VARCHAR(128) NULL,
    trace_id VARCHAR(128) NULL,
    first_processed_at DATETIME(6) NULL,
    last_processed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_business_idempotency_public_id (public_id),
    UNIQUE KEY uk_business_idempotency_operation_key (operation_type, idempotency_key),
    KEY idx_business_idempotency_aggregate (aggregate_type, aggregate_public_id),
    KEY idx_business_idempotency_status (status, updated_at),
    CONSTRAINT chk_business_idempotency_status CHECK (status IN ('processing', 'succeeded', 'rejected', 'failed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
